const help = "Use next commands:" + "\n"
  + "* 'add' - for push new movie;" + "\n"
  + "* 'find' - for filter movies by year or name;" + "\n"
  + "* 'review' - for list all movies from db;" + "\n"
  + "* 'amount' - for echo count of movies."
 const SEARCH_MOVIE = "Please, enter criteria (use 'year' or 'name')"
 const SEARCH_MOVIE_BY = "Please, enter value for criteria"
const hello = "Hello, welcom to film database"
const cmd_ ="You can 'add', 'review','find', ask for 'help', see 'amount' of films or 'exit' "
var film_Name = "Please, enter film name"
const wrong = "Year or name is not correct. Please, check and reenter your data."
let filmY_ = "Please, enter film year"
